### ISSUE TITLE
Bu ne çöplük ya

### ISSUE THREAD

**Issue by taumata666** [CryonicsX/Discord-Spammer#1]
It worked for me thanks a lot

**Comment by Reflechir** [comment]
> çıdlırıcam kardeşim  bu ne ya adam gibi ibişey yazamaın mı mysql mi kullandın bundak ardeşim sude bile hdaha iyi yazardı gir serendaiya cal kodları sonra gel burda paylas bu nasıl bi sey **aptal karı**?

Tau kes götünü sikicem artık

**Comment by taumata666** [comment]
> > çıdlırıcam kardeşim  bu ne ya adam gibi ibişey yazamaın mı mysql mi kullandın bundak ardeşim sude bile hdaha iyi yazardı gir serendaiya cal kodları sonra gel burda paylas bu nasıl bi sey **aptal karı**?
> 
> Tau kes götünü sikicem artık

tavuk mu sikiyon be yarrağım?

**Comment by CryonicsX** [comment]
thanks

**Comment by taumata666** [comment]
Why cloused it?
