### ISSUE TITLE
Mass Join "Error 404"

### ISSUE THREAD

**Issue by pufferfishdev123** [CryonicsX/Discord-Spammer#8]
Tried to make it mass join servers to troll dreamsexual kiddos. Error 404. Checked the tokens I bought, all valid. Why?

**Comment by pufferfishdev123** [comment]
![image](https://user-images.githubusercontent.com/97852890/149677061-c4fbfc87-d59b-4f6b-921e-5918fa9f33b3.png)
Image

**Comment by CryonicsX** [comment]
write me on discord
